### ISSUE TITLE
profunctors-4.4 requires excessive amounts of RAM with GHC 7.10.1-rc1

### ISSUE THREAD

**Issue by peti** [ekmett/profunctors#20] opened 2015-03-07 17:03 UTC
While compiling `Compiling Data.Profunctor.Unsafe` at http://hydra.cryp.to/build/608380/nixlog/7/raw, the `ghc` process goes on allocating memory until it's finally killed by the Linux kernel:

    Out of memory: Kill process 8052 (ghc) score 936 or sacrifice child
    Killed process 8052 (ghc) total-vm:46687868kB, anon-rss:29845192kB, file-rss:712kB

Previous versions of the library did not trigger that behavior.

**Comment by markwright** [comment] 2015-03-08 11:44
Same here with profunctors-4.4.1 ghc 7.10.1-rc1, while compiling Data.Profunctor.Unsafe ghc virtual memory size was growing, reaching 23GB when I had to reboot.

**Comment by ekmett** [comment] 2015-03-08 12:01
Can you try with the second release candidate?

**Comment by ekmett** [comment] 2015-03-08 12:02
There were some problems with Coercible in the first RC as I recall.

**Comment by Twinside** [comment] 2015-03-08 12:44
I can confirm this behavior with GHC 7.10RC2 under windows x64, got the problem this morning.

**Comment by hvr** [comment] 2015-03-08 15:23
Fwiw, I didn't see the issue with 

```
The Glorious Glasgow Haskell Compilation System, version 7.10.0.20150307
```

**Comment by glguy** [comment] 2015-03-09 01:44
You'll need to update your GHC to the 7.10 branch, at least until rc3. There have been fixes to the type system related to Coercible since then. It will be good to update and help test these new fixes.

**Comment by peti** [comment] 2015-03-09 10:08
Where can I find rc3? The latest I see on https://downloads.haskell.org/~ghc/ is rc2.

**Comment by cocreature** [comment] 2015-03-09 10:10
rc3 is not yet released. Afaik the plan is to release it on friday.

**Comment by markwright** [comment] 2015-03-18 01:52
profunctors-4.4.1 builds fine with ghc 7.10.1 rc3 (on Gentoo linux amd64), thanks.

**Comment by ekmett** [comment] 2015-03-18 02:48
Closing this out as it should work from here on out.

**Closed by ekmett** 2015-03-18 02:48 UTC
Labels: compiler-bug, high priority
